version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://dari_user:dari_password@db:5432/dari_wallet
      - ASYNC_DATABASE_URL=postgresql+asyncpg://dari_user:dari_password@db:5432/dari_wallet
      - REDIS_URL=redis://redis:6379/0
      - GANACHE_RPC_URL=http://ganache:8545
      - ALLOWED_ORIGINS=["http://localhost:3000", "https://mybbi.in", "https://dariwallet.com", "https://www.mybbi.in", "https://www.dariwallet.com"]
    depends_on:
      - db
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=dari_wallet
      - POSTGRES_USER=dari_user
      - POSTGRES_PASSWORD=dari_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  ganache:
    image: trufflesuite/ganache-cli:latest
    ports:
      - "8545:8545"
    command: ganache-cli --port 8545 --network-id 1337 --accounts 10 --defaultBalanceEther 100
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data: 